Report `./zh format check` status

diff --git a/zh b/zh
--- a/zh
+++ b/zh
@@ -46,7 +46,15 @@ format)
         exit 1
     esac
     files=$(git ls-files | grep --invert 'vendor/' | grep '.hs$' | grep --invert 'src/ZoomHub/Storage/PostgreSQL/Internal.hs')
+    set +e
     ormolu --mode "$mode" $files
+    ormolu_status=$?
+    set -e
+
+    if [[ "$mode" == "check" && $ormolu_status != 0 ]]; then
+      echo "Ormolu check failed. Exit status: $ormolu_status"
+      exit $ormolu_status
+    fi
     ;;
 run)
     dropdb --if-exists "$DEVELOPMENT_DB_NAME"
